# Generated by Django 4.0 on 2022-03-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(max_length=15)),
                ('groupYearAdmission', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherPhoto', models.ImageField(upload_to='teachers-photos')),
                ('teacherSurname', models.TextField(max_length=50)),
                ('teacherName', models.TextField(max_length=50)),
                ('teacherPatronymic', models.TextField(max_length=50)),
                ('teacherSubjects', models.TextField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='groupTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.teacher'),
        ),
    ]
