# Generated by Django 4.0 on 2022-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_remove_championship_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.TextField(default='', max_length=127),
        ),
    ]
