# Generated by Django 4.0 on 2022-03-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement',
            field=models.FileField(upload_to='diplomas'),
        ),
    ]
