# Generated by Django 4.0 on 2022-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_achievement_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement',
            field=models.ImageField(upload_to='diplomas'),
        ),
    ]
