# Generated by Django 4.0 on 2022-03-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_achievement_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupTeacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
