# Generated by Django 4.0 on 2022-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher'},
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
