# Generated by Django 4.0 on 2022-03-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_teacher_options_alter_group_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupTeacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='customuser_ptr',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
