# Generated by Django 4.0 on 2022-03-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='student',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='group',
            name='groupTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
