# Generated by Django 4.0.5 on 2022-07-13 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_rename_student_achievement_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mainProfile',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
