# Generated by Django 4.0 on 2022-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(max_length=17, unique=True),
        ),
    ]
